### ISSUE TITLE
A few small problems...

### ISSUE THREAD

**Issue by ErrorCodeShadow** [dragoni7/RpgSkillable#1]
Hey, love the mod however there are a few small problems...

Ars Nouveau is listed as an OPTIONAL dependency however I cant get RpgSkillable to run without it.
Some of the tools and armors are missing prerequisites such as; 

-TOOLS
Wood: Shovel, pickaxe, hoe, and sword
Stone: Shovel and pickaxe
Gold: Shovel, pickaxe, hoe, and sword
Iron: Pickaxe
Maybe?: Fishing rod (could have a dexterity prerequisite maybe?) I think the older reskillable versions had it locked behind something.

-ARMORS
Leather: Full set is missing prerequisites
Chainmail: Helmet and boots are missing prerequisites
Iron: Helmet and boots are missing prerequisites
Gold: Helmet, leggings, and boots are missing prerequisites

Hope this helps!

**Comment by dragoni7** [comment]
An update will be out soon to fix the Ars dependency issue!
As for the missing values, I did not add restrictions to those items on purpose. I didn't want the mod to have the same initial restrictions so that the users could tweak and add it themselves.
Those specific armor pieces are missing the restrictions because of the attribute omit option in the config. It prevents armor with attributes below a certain number from having restrictions so anyone can use them. If you want to disable that set the option for endurance attribute omitted values to 0!
The config offers a lot of customization so anything can be tweaked as seen fit!

**Comment by ErrorCodeShadow** [comment]
Oh ok good to know! Thanks for the response. I'll have to take a deep dive into the config.
